# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160528_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Use pen name not real name.', max_length=70, unique=True),
        ),
    ]
